import 'package:quizz_app/models/category_model.dart';

List<CategoryModel> categories = [
    CategoryModel(id: "9", catageoryName: "General Knowledge"),
    CategoryModel(id: "10", catageoryName: "Entertainment: Books"),
    CategoryModel(id: "11", catageoryName: "Entertainment: Film"),
    CategoryModel(id: "12", catageoryName: "Entertainment: Music"),
    CategoryModel(id: "13", catageoryName: "Entertainment: Musicals & Theatres"),
    CategoryModel(id: "14", catageoryName: "Entertainment: Television"),
    CategoryModel(id: "15", catageoryName: "Entertainment: Video Games"),
    CategoryModel(id: "16", catageoryName: "Entertainment: Board Games"),
    CategoryModel(id: "17", catageoryName: "Science & Nature"),
    CategoryModel(id: "18", catageoryName: "Science: Computers"),
    CategoryModel(id: "19", catageoryName: "Science: Mathematics"),
    CategoryModel(id: "20", catageoryName: "Mythology"),
    CategoryModel(id: "21", catageoryName: "Sports"),
    CategoryModel(id: "22", catageoryName: "Geography"),
    CategoryModel(id: "23", catageoryName: "History"),
    CategoryModel(id: "24", catageoryName: "Politics"),
    CategoryModel(id: "25", catageoryName: "Art"),
    CategoryModel(id: "26", catageoryName: "Celebrities"),
    CategoryModel(id: "27", catageoryName: "Animals"),
    CategoryModel(id: "28", catageoryName: "Vehicles"),
    CategoryModel(id: "29", catageoryName: "Entertainment: Comics"),
    CategoryModel(id: "30", catageoryName: "Science: Gadgets"),
    CategoryModel(id: "31", catageoryName: "Entertainment: Japanese Anime & Manga"),
    CategoryModel(id: "32", catageoryName: "Entertainment: Cartoon & Animations"),
  ];