import 'package:quizz_app/models/category_model.dart';

List<CategoryModel> categories = [
    CategoryModel(id: "9", catageoryName: "General Knowledge"),
    CategoryModel(id: "10", catageoryName: "Books"),
    CategoryModel(id: "11", catageoryName: "Film"),
    CategoryModel(id: "12", catageoryName: "Music"),
    CategoryModel(id: "13", catageoryName: "Musicals & Theatres"),
    CategoryModel(id: "14", catageoryName: "Television"),
    CategoryModel(id: "15", catageoryName: "Video Games"),
    CategoryModel(id: "16", catageoryName: "Board Games"),
    CategoryModel(id: "17", catageoryName: "Science & Nature"),
    CategoryModel(id: "18", catageoryName: "Computers"),
    CategoryModel(id: "19", catageoryName: "Mathematics"),
    CategoryModel(id: "20", catageoryName: "Mythology"),
    CategoryModel(id: "21", catageoryName: "Sports"),
    CategoryModel(id: "22", catageoryName: "Geography"),
    CategoryModel(id: "23", catageoryName: "History"),
    CategoryModel(id: "24", catageoryName: "Politics"),
    CategoryModel(id: "25", catageoryName: "Art"),
    CategoryModel(id: "26", catageoryName: "Celebrities"),
    CategoryModel(id: "27", catageoryName: "Animals"),
    CategoryModel(id: "28", catageoryName: "Vehicles"),
    CategoryModel(id: "29", catageoryName: "Comics"),
    CategoryModel(id: "30", catageoryName: "Gadgets"),
    CategoryModel(id: "31", catageoryName: "Japanese Anime & Manga"),
    CategoryModel(id: "32", catageoryName: "Cartoon & Animations"),
  ];